---
title: "American Tv Shows"
description: |
  I'm going to explain here, which Tv shows I prefer and why between Steven Colbert, Trevor Noah, John Oliver, Jimmy Fallon.
author:
  - name: Florian Cosa
    url: {}
date: 10-11-2020
output:
  distill::distill_article:
    self_contained: false
---

So there are four shows :  

* The first one is "The Late Show with Stephen Colbert". It's really good ! I learned some fun facts, but nothing important about actuality. There is a good balance with jokes and serious talk.  

* The second one is "The Daily Show with Trevor Noah". This one is more crude and talks about recent events, He gives his opinion and make fun of others (like Trump). I enjoyed it, but I find Trevor a little bit aggressive.   

* The third one is "Last Week Tonight". I didn't really like this show, I mean it was interesting, but too boring and political for me and the show is pretty long 25 minutes in average.  

* The last one is "The Tonight Show Starring Jimmy Fallon". This short show is only humor (5 minute videos), I don't dislike it, but I didn't learn anything new its just for fun.  

In conclusion, my favorite show is with Stephen Colbert because its easily watchable 5 to 10 minutes and there are some constructive elements put with a lot of humor.  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

